### ISSUE TITLE
Cloudflare Pages support?

### ISSUE THREAD

**Issue by iand675** [cloudflare/workers-honeycomb-logger#10]
Hi, I'm curious about using this with Cloudflare pages? I'm trying out the official Remix support with Cloudflare pages, but it seems like I might not have access to the underlying listener. Can you provide any guidance about how I might go about instrumenting in this case?

**Comment by evanderkoogh** [comment]
Hey @iand675, apologies for the late reply, been a bit busy over the past few weeks. There is indeed currently no easy way to use it in Pages functions. I hope to be able to add support for it in the next week or two.
