### ISSUE TITLE
Misleading log message when forgetting to pass API Key in

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/workers-honeycomb-logger#13]
When attempting to use the environment variables `HONEYCOMB_API_KEY` and `HONEYCOMB_DATASET` (using `wrapModule({}, handler)`  but forgetting to set them in the Workers console, rather than an error explaining this the only error given is a misleading `deprecated endpoint - please upgrade` logged to console (but not thrown).

Reproduction:
1. Install workers-honeycomb-logger normally.
2. Wrap a module but using `wrapModule({}, handler)` (normally you would pass in API Key and Dataset to the first argument but when using environment variables you shouldn't).
3. Forget to set in environment variables for API Key and Dataset 😆.
4. View the logs, where the `deprecated endpoint` error will be shown.

**Comment by evanderkoogh** [comment]
Fixed in 2d6806a142d5ac9186f168869a5da7360dff1dcc. Will release as `2.2.1` once my npm privileges are fixed :)
