### ISSUE TITLE
Error when passing tracer.fetch as argument

### ISSUE THREAD

**Issue by isaac-mcfadyen** [cloudflare/workers-honeycomb-logger#15]
When using `request.tracer.fetch` and passing the fetch function as an argument to another function (for example, into a function that actually runs the fetch) everything breaks with the following error:
```
TypeError: Cannot read properties of undefined (reading 'startChildSpan') at fetch
```

However, if `tracer` is passed in instead and the child function gets fetch off of the tracer (like `await tracer.fetch()` instead of just `await [fetch_as_argument]()`) then everything works fine.

Not sure if this is related to me using `esbuild` to bundle or not.

**Comment by evanderkoogh** [comment]
No, it means that you have to bind `this` to the correct Tracer object.

If you use `fetch.bind(request.tracer)`, it should work..

**Comment by isaac-mcfadyen** [comment]
Oh, perfect. Thanks.
