### ISSUE TITLE
`request.trace.fetch` arg types differ from workers-types

### ISSUE THREAD

**Issue by ptim** [cloudflare/workers-honeycomb-logger#26]
FYI - to install fetch traces for a POST, I need to wrap `fetch(string, RequestInit)` in a Request, like:

```js
// from (truncated)
fetch('http://example.com', { method: 'POST'})

// to:
fetch(new Request('http://example.com', { method: 'POST'}))
```

Just mentioning because: 

> The method on the tracer delegates all arguments to the regular fetch method, so the tracer.fetch function is a drop-in replacement for all fetch function calls.
https://github.com/cloudflare/workers-honeycomb-logger#traces

```ts
// node_modules/@cloudflare/workers-honeycomb-logger/dist/logging.d.ts
fetch(input: Request, init?: RequestInit): Promise<Response>;

// node_modules/@cloudflare/workers-types/index.d.ts
declare abstract class Fetcher {
  fetch(
    requestOrUrl: Request | string,
    requestInit?: RequestInit | Request
  ): Promise<Response>;
}
```

HTH!

**Comment by evanderkoogh** [comment]
Great catch @ptim.. With the new workers-types I can now remove my internal fetch type.. Will fix :)
