### ISSUE TITLE
'TypeError: data.response.headers.get is not a function' in sampleRatesFn

### ISSUE THREAD

**Issue by ptim** [cloudflare/workers-honeycomb-logger#28]
FYI, ran across this in whilst tweaking my `sampleRates` fn 👍

Workaround: use optional chaining: `data.response.headers.get?.("x-A")`

```ts
const honeycombConfig: Partial<ResolvedConfig> = {
  dataset: "test-handler",
  /** https://github.com/cloudflare/workers-honeycomb-logger/#dynamic-sampling */
  sampleRates(data: any): number {
    try {
      console.log(data.response.headers.get?.("x-A")); // safe due to optional chaining
      console.log(data.response.headers.get("x-B")); // throws
    } catch (error) {
      // TypeError: data.response.headers.get is not a function
      // at sampleRates (~/miniflare-typescript-esbuild-jest/src/index.ts:21:41)
      console.error(error);
      /*
      typeof data.response.headers
      'object'

      data.response.headers instanceof Headers
      false
      */
    }
    return 1;
  },
};
```

Repro: https://github.com/ptim/miniflare-typescript-esbuild-jest/blob/repro%2Fhoneycomb-io-redirect-headers-get/src/index.ts#L21 (note that tests pass due to the catch block 👍)

**Comment by evanderkoogh** [comment]
Ah yeah, that is a good point. You cannot JSON-ify the standard Headers class, so I convert it to a Record<string, string>.

So for your case, you would want to use: `data.response.headers['x-A']`
Apologies for the late reply, been a bit buried with other work.

**Comment by evanderkoogh** [comment]
Also.. added a note to the Readme to make that more explicit.. Thanks Tim!
