### ISSUE TITLE
Using vars/secrets for initializing the worker in ESM mode

### ISSUE THREAD

**Issue by frnkhmr** [cloudflare/workers-honeycomb-logger#4]
Hello!
I am just wondering if there might be any tips or way of utilizing secrets/environment variables for the apiKey needed to initialize the library.

```
const worker = {
  async fetch(request, env, ctx) {
    return new Response('Hello world!', { status: 200 })
  },
}

const config = {
  apiKey: '__HONEYCOMB_API_KEY__',
  dataset: 'my-first-dataset',
}

export default wrapModule(config, worker)
```
When using modules the env variables are available in the fetch context for every request but I need to use it earlier. Having the api key embedded in the code is not an option. And I am using Durable Objects so I can't switch back to non ESM code either.

Just looking for some insights! Thank you!

**Comment by isaac-mcfadyen** [comment]
You can set the environment variables `HONEYCOMB_API_KEY` and `HONEYCOMB_DATASET` and they will override whatever is inserted manually.
