### ISSUE TITLE
Typescript workers workaround needed or Typescript compilation fails

### ISSUE THREAD

**Issue by grempe** [cloudflare/workers-honeycomb-logger#7]
I discovered the following workaround was needed in order to setup the listener in a Typescript workers project (such as from the [Cloudflare Typescript Template](https://github.com/cloudflare/worker-typescript-template)):

I found that I had to cast `event` as a `FetchEvent` or Typescript would fail to compile the project. See the commented line below for an example.  It would be very helpful if this would be included in the README samples as this took hours to figure out what was going on and to find a solution.

I would also suggest that the examples baked into this repo include a Typescript sample.

```typescript
import { Config, hc } from '@cloudflare/workers-honeycomb-logger'

// Points to your own handler function, not shown here
import { handleRequest } from './handler'

const hcConfig: Config = {
  apiKey: HONEYCOMB_KEY,
  dataset: `my-project`,
  sampleRates: {
    '1xx': 1,
    '2xx': 1,
    '3xx': 1,
    '4xx': 1,
    '5xx': 1,
    exception: 1,
  },
}

const listener = hc(hcConfig, (event) => {
  // A work around since strict Typescript checks won't allow `event` to be of type `FetchEvent`
  // Without this `respondWith` and `request` are not functions on an `Event` object.
  const fe = event as FetchEvent
  fe.respondWith(handleRequest(fe.request))
})

addEventListener('fetch', listener)
```

**Comment by evanderkoogh** [comment]
Should no longer be needed after Typescript updates a while ago.

**Comment by merykozlowska** [comment]
@evanderkoogh I'm afraid this is still an issue because `wrapEventListener` accepts `EventListener` (so `EventListener<Event>`, not `EventListener<FetchEvent>`) and therefore we can't know that the event passed to the listener will actually be a `FetchEvent`.

Should `wrapEventListener` maybe be a generic function, like this?
```ts
function wrapEventListener<EventType extends Event = Event>(cfg: Config, listener: EventListener<EventType>): EventListener<EventType>
```
