### ISSUE TITLE
Docs : Honeycomb `Automatically unpack nested JSON` needs to be enabled

### ISSUE THREAD

**Issue by grempe** [cloudflare/workers-honeycomb-logger#8]
It would be helpful for those just getting started if the need to turn on `Automatically unpack nested JSON` in the Honeycomb `Dataset Setting > Schema` tab was documented.

I think that without this, you cannot follow traces in Honeycomb's UI as the JSON object sent with the `traces` property doesn't get unpacked for use.

**Comment by evanderkoogh** [comment]
Oh yes, that is a great suggestion. Been using Honeycomb for way too long to remember I spend a bunch of time looking for that too.

Thanks!
